LPARAMETERS lParam, cParam
IF !EMPTY(m.cParam)
	SELECT (m.cParam)
ENDIF
DO CASE
CASE EMPTY(m.lParam)
	SET DELETED OFF
	LOCATE ALL FOR DELETED()=.T.
CASE appdbf4d()
	GO BOTTOM
	SET DELETED OFF
	LOCATE REST FOR DELETED()=.T.
OTHERWISE
	SET DELETED OFF
	LOCATE REST FOR DELETED()=.T.
ENDCASE
IF DELETED()
	RECALL
	BLANK
ELSE
	IF !EMPTY(m.lParam)
		=appdbf4d(1, ALIAS())
	ENDIF
	APPEND BLANK
ENDIF
SET DELETED ON
