LPARAMETERS cParam, lParam
IF IIF(EMPTY(m.cParam), .T., !FILE(cParam+".dbc"))
	RETURN .F.
ENDIF
CLOSE TABLES ALL
CLOSE DATABASES ALL
IF EMPTY(m.lParam)
	SET TABLEVALIDATE TO 0
	SET EXCLUSIVE OFF
	OPEN DATABASE (m.cParam)
ELSE
	SET TABLEVALIDATE TO 3
	SET EXCLUSIVE ON
	OPEN DATABASE (m.cParam)
	cParam=DBC()
	VALIDATE DATABASE NOCONSOLE
	CLOSE DATABASES
	USE (m.cParam)
	COUNT TO lParam
	LOCATE ALL FOR DELETED()=.T.
	IF IIF(m.lParam=RECCOUNT(), FOUND(), .T.)
		PACK
	ENDIF
	IF VAL(SYS(2012))#1
		lParam = SET("Blocksize")
		SET BLOCKSIZE TO 0
		ALTER TABLE (m.cParam) ADD COLUMN mzero M
		ALTER TABLE (m.cParam) DROP COLUMN mzero
		SET BLOCKSIZE TO m.lParam
	ENDIF
	USE
	OPEN DATABASE (m.cParam)
ENDIF
