LPARAMETERS cAlias, cField
IF !EMPTY(cAlias)
	SELECT (cAlias)
ENDIF
IF USED() AND !ISREADONLY()
	IF !EMPTY(cField)
		REPLACE (cField) WITH MONTH(DATE())*100000000+DAY(DATE())*1000000+VAL(RIGHT(SYS(3),6))
	ENDIF
	DELETE
	=appdbf4d(2, ALIAS())
ELSE
	RETURN .F.
ENDIF
