WITH _SCREEN
	IF .Visible
		IF !EMPTY(_CLIPTEXT)
			LOCAL cc, nn, cpoint
			STORE '' TO cc
			STORE SYS(2001, 'POINT') TO cpoint		&&SYS(2001,'SEPARATOR') + 
			FOR nn=1 TO LEN(_CLIPTEXT)
				STORE cc + IIF(IIF(ISDIGIT(SUBSTR(_CLIPTEXT, nn, 1)), .T., SUBSTR(_CLIPTEXT, nn, 1)$cpoint), SUBSTR(_CLIPTEXT, nn, 1), "") TO cc
			ENDFOR
			IF !EMPTY(VAL(cc))
				STORE VAL(cc) TO _CALCVALUE
			ENDIF
		ENDIF
		ACTIVATE WINDOW CALCULATOR TOP
	ELSE
		RUN /N1 CALC.EXE
	ENDIF
ENDWITH
