LPARAMETERS nParam
DO CASE
CASE EMPTY(m.nParam)
	IF !USED("quote")
		USE club!quote IN 0
	ENDIF
	SELECT quote
CASE m.nParam=1
	DO vfpclubdefault WITH 0
	
	DELETE ALL FOR BETWEEN(iquote, -121, 0)=.T.
	
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-1, '[b]', '<b>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-2, '[/b]', '</b>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-3, '[i]', '<i>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-4, '[/i]', '</i>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-5, '[s]', '<s>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-6, '[/s]', '</s>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-7, '[u]', '<u>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-8, '[/u]', '</u>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-9, '[h]', '<h>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-10, '[/h]', '</h>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-11, '[pre]', '<pre>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-12, '[/pre]', '</pre>')

	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-21, '[list]', '<ol>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-22, '[/list]', '</ol>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-23, '[small]', '<small>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-24, '[/small]', '</small>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-25, '[sub]', '<sub>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-26, '[/sub]', '</sub>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-27, '[sup]', '<sup>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-28, '[/sup]', '</sup>')

	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-41, '[quote]', '<blockquote class="bbcode"><br><div>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-42, '[/quote]', '</div></blockquote>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-43, '[code]', '<pre class="bbcode">')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-44, '[/code]', '</pre>')

	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-51, '[/color]', '</span>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-52, '[color=Blue]', '<span style="color: Blue">')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-53, '[color=Gray]', '<span style="color: Gray">')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-54, '[color=Green]', '<span style="color: Green">')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (-55, '[color=Red]', '<span style="color: Red">')

	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-59, ':eyes:', 'eyes.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-60, '[sm020]', '020.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-61, '[sm016]', '016.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-62, '[sm017]', '017.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-63, '[sm021]', '021.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-64, '[sm039]', '039.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-65, '[sm055]', '55.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-66, '[sm128]', '128.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-67, ':danc:', 'ap.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-68, ':doom:', 'an.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-69, ':kiss:', 'aj.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-70, ':love:', 'ax.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-71, ':spy:', 'spy.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-72, ':gigi:', 'gigi.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-73, ':rotate:', 'rotate.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-74, ':)', 'smile.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-75, ':rotate:', 'rotate.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-76, ':beer:', 'beer.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-77, ':shuffle:', 'shuffle.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-78, ':-p', 'ae.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-79, ':moder:', 'moder.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-80, ':lol:', 'lol.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-81, ':lough:', 'laugh.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-82, ':D', 'biggrin.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-83, ':(', 'frown.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-84, ':mad:', 'mad.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-85, ':super:', 'super.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-86, ':p:', 'tongue.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-87, ':bodr:', 'ar.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-88, ':weep:', 'weep.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-89, ':-\', 'smirk.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-90, ':cool:', 'cool.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-91, ':confused:', 'confused.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-92, ':eek:', 'eek.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-93, ':rolleyes:', 'rolleyes.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-94, ':insane:', 'insane.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-95, ':pofig:', 'pofig.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-96, ':idea:', 'idea.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-97, ':puke:', 'puke.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-98, ':beer2:', 'az.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-99, ':urra:', 'ura.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-100, ':xixi:', 'ag.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-101, ':sos:', 'bc.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-102, ':al:', 'al.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-103, ':ao:', 'ao.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-104, ':bi:', 'bi.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-105, ':-[', 'ah.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-106, ';o)', 'smile.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-107, ':-D', 'biggrin.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-108, '[sm20]', '020.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-109, ':-)', 'smile.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-110, ';-)', 'smile.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-111, '.;)', 'wink.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-112, '\m/', 'bd.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-113, ';)', 'wink.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-114, ':o', 'redface.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-115, '[rtfm]', 'rtfm.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-116, '(to)', 'smiley24.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-117, ':ct:', 'close_te.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-118, '<g>', 'smile000.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-119, ':hi:', 'hi.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-120, ':love1:', 'give_heart.gif', .T.)
	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (-121, ':rux:', 'russian.gif', .T.)

CASE m.nParam=2
	DO vfpclubdefault WITH 0
	
	DELETE ALL FOR BETWEEN(iquote, 0, 42)=.T.
	INSERT INTO quote (iquote, cquote) VALUES (1, '[b]')
	INSERT INTO quote (iquote, cquote) VALUES (2, '[/b]')
	INSERT INTO quote (iquote, cquote) VALUES (3, '[i]')
	INSERT INTO quote (iquote, cquote) VALUES (4, '[/i]')
	INSERT INTO quote (iquote, cquote) VALUES (5, '[s]')
	INSERT INTO quote (iquote, cquote) VALUES (6, '[/s]')
	INSERT INTO quote (iquote, cquote) VALUES (7, '[u]')
	INSERT INTO quote (iquote, cquote) VALUES (8, '[/u]')
	INSERT INTO quote (iquote, cquote) VALUES (9, '[h]')
	INSERT INTO quote (iquote, cquote) VALUES (10, '[/h]')
	INSERT INTO quote (iquote, cquote) VALUES (11, '[pre]')
	INSERT INTO quote (iquote, cquote) VALUES (12, '[/pre]')

	INSERT INTO quote (iquote, cquote) VALUES (21, '[list]')
	INSERT INTO quote (iquote, cquote) VALUES (22, '[/list]')
	INSERT INTO quote (iquote, cquote) VALUES (23, '[small]')
	INSERT INTO quote (iquote, cquote) VALUES (24, '[/small]')
	INSERT INTO quote (iquote, cquote) VALUES (25, '[sub]')
	INSERT INTO quote (iquote, cquote) VALUES (26, '[/sub]')
	INSERT INTO quote (iquote, cquote) VALUES (27, '[sup]')
	INSERT INTO quote (iquote, cquote) VALUES (28, '[/sup]')

	INSERT INTO quote (iquote, cquote, cquote2) VALUES (31, '&quot;', '"')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (32, '&amp;', '&')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (33, '&lt;', '<')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (34, '&gt;', '>')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (35, '&laquo;', '´')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (36, '&raquo;', 'ª')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (37, '&mdash;', 'ó')
	INSERT INTO quote (iquote, cquote, cquote2) VALUES (38, '&ndash;', 'ñ')

	INSERT INTO quote (iquote, cquote, cquote2, lquote) VALUES (41, '[quote]', '÷ËÚ‡Ú‡:', .T.)
	INSERT INTO quote (iquote, cquote, lquote) VALUES (42, '[/quote]', .T.)
ENDCASE
